### ISSUE TITLE
🚀 Feature: track Lobbies created by a User

### ISSUE THREAD

**Issue by trevorong** [UCLA-Creative-Labs/aurgy-backend#28]
[Design doc notes](https://github.com/UCLA-Creative-Labs/aurgy-backend/blob/main/docs/DESIGN_DOC.md#users)

- Add a way for a User object to track what Lobbies it has created as well as what lobbies a User is currently joined in.
- Make the helper function createLobby inside User that should invoke Lobby.create to create the lobby, then update the User's managedLobbies and participatingLobbies lists.

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by BryanPan342** [comment]
#36 closes this issue
