### ISSUE TITLE
🐛 Bug: add validateUserJwt middleware to lobby/id endpoints GET, PATCH, DELETE

### ISSUE THREAD

**Issue by darren2hang** [UCLA-Creative-Labs/aurgy-backend#34]
The GET, PATCH, DELETE endpoints for lobby/id don't validate the user. This will result in an error on the frontend side if they follow the current design doc when constructing their requests.

### Suggestions

Add the validateUserJwt middleware function to the GET, PATCH, and DELETE endpoints for lobby/id

--- 

This is a :bug: Bug Report

**Comment by BryanPan342** [comment]
i think #36 completes this but we should test!
